version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: admin
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
