version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: admin
    volumes:
      - oracle-data:/opt/oracle/oradata

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  oracle-data:
  redis-data: